# Generated by Django 3.0.4 on 2020-03-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20200327_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='is_data_provided',
            field=models.BooleanField(default=False),
        ),
    ]
