# Generated by Django 3.0.4 on 2020-04-06 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20200401_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='event',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='waitinglist',
            name='event',
        ),
        migrations.RemoveField(
            model_name='waitinglist',
            name='participant',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
        migrations.DeleteModel(
            name='WaitingList',
        ),
    ]
